#!/usr/bin/env bash
set -e

CONFIG_SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


cd "${BASEDIR}"
sudo ./install_i3.sh
sudo apt install zsh curl rofi i3blocks vim emacs nano terminator wget 
sudo ./install_sublime.sh
sudo ./install_chrome.sh
sudo chsh -s $(which zsh)

git submodule update --init --recursive "${DOTBOT_DIR}"
mkdir ~/code
mkdir ~/data
mkdir ~/envs
mkdir ~/temp
# base lib
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "default${CONFIG_SUFFIX}"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
set +e
